version: '3.3'
services:
  vrising:
    build: .
    container_name: vrising
    # image: trueosiris/vrising
    network_mode: bridge
    environment:
      - TZ=America/Argentina/Mendoza
      - SERVERNAME=Pandemonium
      - GAMEPORT=27015
      - QUERYPORT=27016
    volumes:
      - './server:/mnt/vrising/server:rw'
      - './data:/mnt/vrising/persistentdata:rw'
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
      - '27015:27015/tcp'
      - '27036:27036/tcp'
      - '27015:27015/udp'
      - '27016:27016/udp'
      - '27031-27036:27031-27036/udp'
      - '25575:25575'